version: '3.7'
services:
  redis:
    image: 'redis'
    ports:
      - "6379:6379"
    hostname: redis
  web:
    build: .
    ports: 
      - "4000:4000"
    environment:
      - PORT=4000
      - REDIS_HOST=redis
      