version: "3.7"
services:
  redis:
    image: 'redis'
    ports:
      - "6379:6379"
    volumes:
      # - db-data:/foo
      - $PWD/redis-data:/var/lib/redis
    hostname: redis
  web:
    build:
      context: .
      args: 
        NODE_ENV: production
    ports: 
      - "4000:4000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
    command: npm start

# networks:
#   benet:
#     driver: bridge
volumes:
  db-data:
